// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/wargasipil/facego/internal/services/attendance_service"
	"github.com/wargasipil/facego/internal/services/auth_service"
	"github.com/wargasipil/facego/internal/services/class_service"
	"github.com/wargasipil/facego/internal/services/face_embedding_service"
	"github.com/wargasipil/facego/internal/services/grade_service"
	"github.com/wargasipil/facego/internal/services/notifier_service"
	"github.com/wargasipil/facego/internal/services/study_program_service"
	"github.com/wargasipil/facego/internal/services/teacher_service"
	"github.com/wargasipil/facego/internal/services/user_service"
	"github.com/wargasipil/facego/internal/services/whatsapp_service"
)

// Injectors from wire.go:

func initApp() (App, error) {
	appConfig, err := NewConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	authServiceHandler := auth_service.NewService(db, appConfig)
	gradeServiceHandler := grade_service.NewService(db)
	studyProgramServiceHandler := study_program_service.NewService(db)
	classServiceHandler := class_service.NewService(db)
	userServiceHandler := user_service.NewService(db, appConfig)
	teacherServiceHandler := teacher_service.NewService(db)
	service := attendance_service.NewService(db)
	faceEmbeddingServiceHandler := face_embedding_service.NewService(db)
	whatsappServiceHandler, err := whatsapp_service.NewService(db)
	if err != nil {
		return nil, err
	}
	notifierServiceHandler := notifier_service.NewService(db)
	apiRunner := NewApiRunner(db, appConfig, authServiceHandler, gradeServiceHandler, studyProgramServiceHandler, classServiceHandler, userServiceHandler, teacherServiceHandler, service, faceEmbeddingServiceHandler, whatsappServiceHandler, notifierServiceHandler)
	notifierRunnerFunc := notifier_service.NewNotifierRunner(whatsappServiceHandler, db)
	attendanceProcessorFunc := attendance_service.NewAttendanceProcessor(db)
	appRunnerFunc := NewAppRunner(apiRunner, notifierRunnerFunc, attendanceProcessorFunc)
	autoMigrateFunc := NewAutoMigrate(appConfig, db)
	seedFunc := NewSeed(db, appConfig, authServiceHandler, userServiceHandler, classServiceHandler)
	app := NewApp(appRunnerFunc, autoMigrateFunc, seedFunc)
	return app, nil
}
