// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: faces/v1/faces.proto

package facesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wargasipil/student_pack/interfaces/faces/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FaceServiceName is the fully-qualified name of the FaceService service.
	FaceServiceName = "faces.v1.FaceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FaceServiceFaceRegisterProcedure is the fully-qualified name of the FaceService's FaceRegister
	// RPC.
	FaceServiceFaceRegisterProcedure = "/faces.v1.FaceService/FaceRegister"
)

// FaceServiceClient is a client for the faces.v1.FaceService service.
type FaceServiceClient interface {
	FaceRegister(context.Context, *connect.Request[v1.FaceRegisterRequest]) (*connect.Response[v1.FaceRegisterResponse], error)
}

// NewFaceServiceClient constructs a client for the faces.v1.FaceService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFaceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FaceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	faceServiceMethods := v1.File_faces_v1_faces_proto.Services().ByName("FaceService").Methods()
	return &faceServiceClient{
		faceRegister: connect.NewClient[v1.FaceRegisterRequest, v1.FaceRegisterResponse](
			httpClient,
			baseURL+FaceServiceFaceRegisterProcedure,
			connect.WithSchema(faceServiceMethods.ByName("FaceRegister")),
			connect.WithClientOptions(opts...),
		),
	}
}

// faceServiceClient implements FaceServiceClient.
type faceServiceClient struct {
	faceRegister *connect.Client[v1.FaceRegisterRequest, v1.FaceRegisterResponse]
}

// FaceRegister calls faces.v1.FaceService.FaceRegister.
func (c *faceServiceClient) FaceRegister(ctx context.Context, req *connect.Request[v1.FaceRegisterRequest]) (*connect.Response[v1.FaceRegisterResponse], error) {
	return c.faceRegister.CallUnary(ctx, req)
}

// FaceServiceHandler is an implementation of the faces.v1.FaceService service.
type FaceServiceHandler interface {
	FaceRegister(context.Context, *connect.Request[v1.FaceRegisterRequest]) (*connect.Response[v1.FaceRegisterResponse], error)
}

// NewFaceServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFaceServiceHandler(svc FaceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	faceServiceMethods := v1.File_faces_v1_faces_proto.Services().ByName("FaceService").Methods()
	faceServiceFaceRegisterHandler := connect.NewUnaryHandler(
		FaceServiceFaceRegisterProcedure,
		svc.FaceRegister,
		connect.WithSchema(faceServiceMethods.ByName("FaceRegister")),
		connect.WithHandlerOptions(opts...),
	)
	return "/faces.v1.FaceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FaceServiceFaceRegisterProcedure:
			faceServiceFaceRegisterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFaceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFaceServiceHandler struct{}

func (UnimplementedFaceServiceHandler) FaceRegister(context.Context, *connect.Request[v1.FaceRegisterRequest]) (*connect.Response[v1.FaceRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("faces.v1.FaceService.FaceRegister is not implemented"))
}
