// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: attendance/v1/attendance.proto

package attendance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_attendance_v1_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_v1_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_attendance_v1_attendance_proto_rawDescGZIP(), []int{0}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_attendance_v1_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_v1_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_attendance_v1_attendance_proto_rawDescGZIP(), []int{1}
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_attendance_v1_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_v1_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_attendance_v1_attendance_proto_rawDescGZIP(), []int{2}
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_attendance_v1_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_attendance_v1_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_attendance_v1_attendance_proto_rawDescGZIP(), []int{3}
}

var File_attendance_v1_attendance_proto protoreflect.FileDescriptor

const file_attendance_v1_attendance_proto_rawDesc = "" +
	"\n" +
	"\x1eattendance/v1/attendance.proto\x12\rattendance.v1\"\r\n" +
	"\vListRequest\"\x0e\n" +
	"\fListResponse\"\x0f\n" +
	"\rSubmitRequest\"\x10\n" +
	"\x0eSubmitResponse2\x9d\x01\n" +
	"\x11AttendanceService\x12G\n" +
	"\x06Submit\x12\x1c.attendance.v1.SubmitRequest\x1a\x1d.attendance.v1.SubmitResponse(\x01\x12?\n" +
	"\x04List\x12\x1a.attendance.v1.ListRequest\x1a\x1b.attendance.v1.ListResponseB\xc1\x01\n" +
	"\x11com.attendance.v1B\x0fAttendanceProtoP\x01ZFgithub.com/wargasipil/student_pack/interfaces/attendance/v1;attendance\xa2\x02\x03AXX\xaa\x02\rAttendance.V1\xca\x02\rAttendance\\V1\xe2\x02\x19Attendance\\V1\\GPBMetadata\xea\x02\x0eAttendance::V1b\x06proto3"

var (
	file_attendance_v1_attendance_proto_rawDescOnce sync.Once
	file_attendance_v1_attendance_proto_rawDescData []byte
)

func file_attendance_v1_attendance_proto_rawDescGZIP() []byte {
	file_attendance_v1_attendance_proto_rawDescOnce.Do(func() {
		file_attendance_v1_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_attendance_v1_attendance_proto_rawDesc), len(file_attendance_v1_attendance_proto_rawDesc)))
	})
	return file_attendance_v1_attendance_proto_rawDescData
}

var file_attendance_v1_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_attendance_v1_attendance_proto_goTypes = []any{
	(*ListRequest)(nil),    // 0: attendance.v1.ListRequest
	(*ListResponse)(nil),   // 1: attendance.v1.ListResponse
	(*SubmitRequest)(nil),  // 2: attendance.v1.SubmitRequest
	(*SubmitResponse)(nil), // 3: attendance.v1.SubmitResponse
}
var file_attendance_v1_attendance_proto_depIdxs = []int32{
	2, // 0: attendance.v1.AttendanceService.Submit:input_type -> attendance.v1.SubmitRequest
	0, // 1: attendance.v1.AttendanceService.List:input_type -> attendance.v1.ListRequest
	3, // 2: attendance.v1.AttendanceService.Submit:output_type -> attendance.v1.SubmitResponse
	1, // 3: attendance.v1.AttendanceService.List:output_type -> attendance.v1.ListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_attendance_v1_attendance_proto_init() }
func file_attendance_v1_attendance_proto_init() {
	if File_attendance_v1_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_attendance_v1_attendance_proto_rawDesc), len(file_attendance_v1_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_attendance_v1_attendance_proto_goTypes,
		DependencyIndexes: file_attendance_v1_attendance_proto_depIdxs,
		MessageInfos:      file_attendance_v1_attendance_proto_msgTypes,
	}.Build()
	File_attendance_v1_attendance_proto = out.File
	file_attendance_v1_attendance_proto_goTypes = nil
	file_attendance_v1_attendance_proto_depIdxs = nil
}
