// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: whatsapp/v1/whatsapp.proto

package whatsapp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WStreamRequest) Reset() {
	*x = WStreamRequest{}
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WStreamRequest) ProtoMessage() {}

func (x *WStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WStreamRequest.ProtoReflect.Descriptor instead.
func (*WStreamRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_v1_whatsapp_proto_rawDescGZIP(), []int{0}
}

type NeedLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedLogin) Reset() {
	*x = NeedLogin{}
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedLogin) ProtoMessage() {}

func (x *NeedLogin) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedLogin.ProtoReflect.Descriptor instead.
func (*NeedLogin) Descriptor() ([]byte, []int) {
	return file_whatsapp_v1_whatsapp_proto_rawDescGZIP(), []int{1}
}

func (x *NeedLogin) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type WStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to E:
	//
	//	*WStreamResponse_NeedLogin
	//	*WStreamResponse_SyncCompleted
	E             isWStreamResponse_E `protobuf_oneof:"e"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WStreamResponse) Reset() {
	*x = WStreamResponse{}
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WStreamResponse) ProtoMessage() {}

func (x *WStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WStreamResponse.ProtoReflect.Descriptor instead.
func (*WStreamResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_v1_whatsapp_proto_rawDescGZIP(), []int{2}
}

func (x *WStreamResponse) GetE() isWStreamResponse_E {
	if x != nil {
		return x.E
	}
	return nil
}

func (x *WStreamResponse) GetNeedLogin() *NeedLogin {
	if x != nil {
		if x, ok := x.E.(*WStreamResponse_NeedLogin); ok {
			return x.NeedLogin
		}
	}
	return nil
}

func (x *WStreamResponse) GetSyncCompleted() bool {
	if x != nil {
		if x, ok := x.E.(*WStreamResponse_SyncCompleted); ok {
			return x.SyncCompleted
		}
	}
	return false
}

type isWStreamResponse_E interface {
	isWStreamResponse_E()
}

type WStreamResponse_NeedLogin struct {
	NeedLogin *NeedLogin `protobuf:"bytes,1,opt,name=need_login,json=needLogin,proto3,oneof"`
}

type WStreamResponse_SyncCompleted struct {
	SyncCompleted bool `protobuf:"varint,2,opt,name=sync_completed,json=syncCompleted,proto3,oneof"`
}

func (*WStreamResponse_NeedLogin) isWStreamResponse_E() {}

func (*WStreamResponse_SyncCompleted) isWStreamResponse_E() {}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_whatsapp_v1_whatsapp_proto_rawDescGZIP(), []int{3}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whatsapp_v1_whatsapp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_whatsapp_v1_whatsapp_proto_rawDescGZIP(), []int{4}
}

var File_whatsapp_v1_whatsapp_proto protoreflect.FileDescriptor

const file_whatsapp_v1_whatsapp_proto_rawDesc = "" +
	"\n" +
	"\x1awhatsapp/v1/whatsapp.proto\x12\vwhatsapp.v1\"\x10\n" +
	"\x0eWStreamRequest\"\x1f\n" +
	"\tNeedLogin\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"x\n" +
	"\x0fWStreamResponse\x127\n" +
	"\n" +
	"need_login\x18\x01 \x01(\v2\x16.whatsapp.v1.NeedLoginH\x00R\tneedLogin\x12'\n" +
	"\x0esync_completed\x18\x02 \x01(\bH\x00R\rsyncCompletedB\x03\n" +
	"\x01e\"\x0f\n" +
	"\rStatusRequest\"\x10\n" +
	"\x0eStatusResponse2\x9c\x01\n" +
	"\x0fWhatsappService\x12A\n" +
	"\x06Status\x12\x1a.whatsapp.v1.StatusRequest\x1a\x1b.whatsapp.v1.StatusResponse\x12F\n" +
	"\aWStream\x12\x1b.whatsapp.v1.WStreamRequest\x1a\x1c.whatsapp.v1.WStreamResponse0\x01B\xb1\x01\n" +
	"\x0fcom.whatsapp.v1B\rWhatsappProtoP\x01ZBgithub.com/wargasipil/student_pack/interfaces/whatsapp/v1;whatsapp\xa2\x02\x03WXX\xaa\x02\vWhatsapp.V1\xca\x02\vWhatsapp\\V1\xe2\x02\x17Whatsapp\\V1\\GPBMetadata\xea\x02\fWhatsapp::V1b\x06proto3"

var (
	file_whatsapp_v1_whatsapp_proto_rawDescOnce sync.Once
	file_whatsapp_v1_whatsapp_proto_rawDescData []byte
)

func file_whatsapp_v1_whatsapp_proto_rawDescGZIP() []byte {
	file_whatsapp_v1_whatsapp_proto_rawDescOnce.Do(func() {
		file_whatsapp_v1_whatsapp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whatsapp_v1_whatsapp_proto_rawDesc), len(file_whatsapp_v1_whatsapp_proto_rawDesc)))
	})
	return file_whatsapp_v1_whatsapp_proto_rawDescData
}

var file_whatsapp_v1_whatsapp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_whatsapp_v1_whatsapp_proto_goTypes = []any{
	(*WStreamRequest)(nil),  // 0: whatsapp.v1.WStreamRequest
	(*NeedLogin)(nil),       // 1: whatsapp.v1.NeedLogin
	(*WStreamResponse)(nil), // 2: whatsapp.v1.WStreamResponse
	(*StatusRequest)(nil),   // 3: whatsapp.v1.StatusRequest
	(*StatusResponse)(nil),  // 4: whatsapp.v1.StatusResponse
}
var file_whatsapp_v1_whatsapp_proto_depIdxs = []int32{
	1, // 0: whatsapp.v1.WStreamResponse.need_login:type_name -> whatsapp.v1.NeedLogin
	3, // 1: whatsapp.v1.WhatsappService.Status:input_type -> whatsapp.v1.StatusRequest
	0, // 2: whatsapp.v1.WhatsappService.WStream:input_type -> whatsapp.v1.WStreamRequest
	4, // 3: whatsapp.v1.WhatsappService.Status:output_type -> whatsapp.v1.StatusResponse
	2, // 4: whatsapp.v1.WhatsappService.WStream:output_type -> whatsapp.v1.WStreamResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_whatsapp_v1_whatsapp_proto_init() }
func file_whatsapp_v1_whatsapp_proto_init() {
	if File_whatsapp_v1_whatsapp_proto != nil {
		return
	}
	file_whatsapp_v1_whatsapp_proto_msgTypes[2].OneofWrappers = []any{
		(*WStreamResponse_NeedLogin)(nil),
		(*WStreamResponse_SyncCompleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whatsapp_v1_whatsapp_proto_rawDesc), len(file_whatsapp_v1_whatsapp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whatsapp_v1_whatsapp_proto_goTypes,
		DependencyIndexes: file_whatsapp_v1_whatsapp_proto_depIdxs,
		MessageInfos:      file_whatsapp_v1_whatsapp_proto_msgTypes,
	}.Build()
	File_whatsapp_v1_whatsapp_proto = out.File
	file_whatsapp_v1_whatsapp_proto_goTypes = nil
	file_whatsapp_v1_whatsapp_proto_depIdxs = nil
}
