// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: faces/v1/faces.proto

package faces

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaceRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceRegisterRequest) Reset() {
	*x = FaceRegisterRequest{}
	mi := &file_faces_v1_faces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceRegisterRequest) ProtoMessage() {}

func (x *FaceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faces_v1_faces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceRegisterRequest.ProtoReflect.Descriptor instead.
func (*FaceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_faces_v1_faces_proto_rawDescGZIP(), []int{0}
}

type FaceRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaceRegisterResponse) Reset() {
	*x = FaceRegisterResponse{}
	mi := &file_faces_v1_faces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaceRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceRegisterResponse) ProtoMessage() {}

func (x *FaceRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faces_v1_faces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceRegisterResponse.ProtoReflect.Descriptor instead.
func (*FaceRegisterResponse) Descriptor() ([]byte, []int) {
	return file_faces_v1_faces_proto_rawDescGZIP(), []int{1}
}

var File_faces_v1_faces_proto protoreflect.FileDescriptor

const file_faces_v1_faces_proto_rawDesc = "" +
	"\n" +
	"\x14faces/v1/faces.proto\x12\bfaces.v1\"\x15\n" +
	"\x13FaceRegisterRequest\"\x16\n" +
	"\x14FaceRegisterResponse2\\\n" +
	"\vFaceService\x12M\n" +
	"\fFaceRegister\x12\x1d.faces.v1.FaceRegisterRequest\x1a\x1e.faces.v1.FaceRegisterResponseB\x99\x01\n" +
	"\fcom.faces.v1B\n" +
	"FacesProtoP\x01Z<github.com/wargasipil/student_pack/interfaces/faces/v1;faces\xa2\x02\x03FXX\xaa\x02\bFaces.V1\xca\x02\bFaces\\V1\xe2\x02\x14Faces\\V1\\GPBMetadata\xea\x02\tFaces::V1b\x06proto3"

var (
	file_faces_v1_faces_proto_rawDescOnce sync.Once
	file_faces_v1_faces_proto_rawDescData []byte
)

func file_faces_v1_faces_proto_rawDescGZIP() []byte {
	file_faces_v1_faces_proto_rawDescOnce.Do(func() {
		file_faces_v1_faces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_faces_v1_faces_proto_rawDesc), len(file_faces_v1_faces_proto_rawDesc)))
	})
	return file_faces_v1_faces_proto_rawDescData
}

var file_faces_v1_faces_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_faces_v1_faces_proto_goTypes = []any{
	(*FaceRegisterRequest)(nil),  // 0: faces.v1.FaceRegisterRequest
	(*FaceRegisterResponse)(nil), // 1: faces.v1.FaceRegisterResponse
}
var file_faces_v1_faces_proto_depIdxs = []int32{
	0, // 0: faces.v1.FaceService.FaceRegister:input_type -> faces.v1.FaceRegisterRequest
	1, // 1: faces.v1.FaceService.FaceRegister:output_type -> faces.v1.FaceRegisterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faces_v1_faces_proto_init() }
func file_faces_v1_faces_proto_init() {
	if File_faces_v1_faces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_faces_v1_faces_proto_rawDesc), len(file_faces_v1_faces_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faces_v1_faces_proto_goTypes,
		DependencyIndexes: file_faces_v1_faces_proto_depIdxs,
		MessageInfos:      file_faces_v1_faces_proto_msgTypes,
	}.Build()
	File_faces_v1_faces_proto = out.File
	file_faces_v1_faces_proto_goTypes = nil
	file_faces_v1_faces_proto_depIdxs = nil
}
