// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/wargasipil/student_pack/webutils"
	"github.com/wargasipil/student_pack/whatsapp_service"
	"net/http"
)

// Injectors from wire.go:

func InitializeApp() (App, error) {
	appConfig := NewConfig()
	serveMux := http.NewServeMux()
	reflectRegisterFunc := webutils.NewReflectRegister(serveMux)
	defaultInterceptor := webutils.NewDefaultInterceptor()
	registerFunc := whatsapp_service.NewRegister(serveMux, defaultInterceptor)
	serveFrontendFunc := NewServeFrontend()
	webAction := NewWebAction(appConfig, serveMux, reflectRegisterFunc, registerFunc, serveFrontendFunc)
	app := NewApp(webAction)
	return app, nil
}
