// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: whatsapp/v1/whatsapp.proto

package whatsappconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wargasipil/student_pack/interfaces/whatsapp/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WhatsappServiceName is the fully-qualified name of the WhatsappService service.
	WhatsappServiceName = "whatsapp.v1.WhatsappService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WhatsappServiceStatusProcedure is the fully-qualified name of the WhatsappService's Status RPC.
	WhatsappServiceStatusProcedure = "/whatsapp.v1.WhatsappService/Status"
	// WhatsappServiceWStreamProcedure is the fully-qualified name of the WhatsappService's WStream RPC.
	WhatsappServiceWStreamProcedure = "/whatsapp.v1.WhatsappService/WStream"
)

// WhatsappServiceClient is a client for the whatsapp.v1.WhatsappService service.
type WhatsappServiceClient interface {
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	WStream(context.Context, *connect.Request[v1.WStreamRequest]) (*connect.ServerStreamForClient[v1.WStreamResponse], error)
}

// NewWhatsappServiceClient constructs a client for the whatsapp.v1.WhatsappService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWhatsappServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WhatsappServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	whatsappServiceMethods := v1.File_whatsapp_v1_whatsapp_proto.Services().ByName("WhatsappService").Methods()
	return &whatsappServiceClient{
		status: connect.NewClient[v1.StatusRequest, v1.StatusResponse](
			httpClient,
			baseURL+WhatsappServiceStatusProcedure,
			connect.WithSchema(whatsappServiceMethods.ByName("Status")),
			connect.WithClientOptions(opts...),
		),
		wStream: connect.NewClient[v1.WStreamRequest, v1.WStreamResponse](
			httpClient,
			baseURL+WhatsappServiceWStreamProcedure,
			connect.WithSchema(whatsappServiceMethods.ByName("WStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// whatsappServiceClient implements WhatsappServiceClient.
type whatsappServiceClient struct {
	status  *connect.Client[v1.StatusRequest, v1.StatusResponse]
	wStream *connect.Client[v1.WStreamRequest, v1.WStreamResponse]
}

// Status calls whatsapp.v1.WhatsappService.Status.
func (c *whatsappServiceClient) Status(ctx context.Context, req *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return c.status.CallUnary(ctx, req)
}

// WStream calls whatsapp.v1.WhatsappService.WStream.
func (c *whatsappServiceClient) WStream(ctx context.Context, req *connect.Request[v1.WStreamRequest]) (*connect.ServerStreamForClient[v1.WStreamResponse], error) {
	return c.wStream.CallServerStream(ctx, req)
}

// WhatsappServiceHandler is an implementation of the whatsapp.v1.WhatsappService service.
type WhatsappServiceHandler interface {
	Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error)
	WStream(context.Context, *connect.Request[v1.WStreamRequest], *connect.ServerStream[v1.WStreamResponse]) error
}

// NewWhatsappServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWhatsappServiceHandler(svc WhatsappServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	whatsappServiceMethods := v1.File_whatsapp_v1_whatsapp_proto.Services().ByName("WhatsappService").Methods()
	whatsappServiceStatusHandler := connect.NewUnaryHandler(
		WhatsappServiceStatusProcedure,
		svc.Status,
		connect.WithSchema(whatsappServiceMethods.ByName("Status")),
		connect.WithHandlerOptions(opts...),
	)
	whatsappServiceWStreamHandler := connect.NewServerStreamHandler(
		WhatsappServiceWStreamProcedure,
		svc.WStream,
		connect.WithSchema(whatsappServiceMethods.ByName("WStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/whatsapp.v1.WhatsappService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WhatsappServiceStatusProcedure:
			whatsappServiceStatusHandler.ServeHTTP(w, r)
		case WhatsappServiceWStreamProcedure:
			whatsappServiceWStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWhatsappServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWhatsappServiceHandler struct{}

func (UnimplementedWhatsappServiceHandler) Status(context.Context, *connect.Request[v1.StatusRequest]) (*connect.Response[v1.StatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("whatsapp.v1.WhatsappService.Status is not implemented"))
}

func (UnimplementedWhatsappServiceHandler) WStream(context.Context, *connect.Request[v1.WStreamRequest], *connect.ServerStream[v1.WStreamResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("whatsapp.v1.WhatsappService.WStream is not implemented"))
}
