// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: users/v1/user.proto

package usersconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wargasipil/student_pack/interfaces/users/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StudentServiceName is the fully-qualified name of the StudentService service.
	StudentServiceName = "users.v1.StudentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StudentServiceStudentCreateProcedure is the fully-qualified name of the StudentService's
	// StudentCreate RPC.
	StudentServiceStudentCreateProcedure = "/users.v1.StudentService/StudentCreate"
	// StudentServiceStudentListProcedure is the fully-qualified name of the StudentService's
	// StudentList RPC.
	StudentServiceStudentListProcedure = "/users.v1.StudentService/StudentList"
	// StudentServiceStudentUpdateProcedure is the fully-qualified name of the StudentService's
	// StudentUpdate RPC.
	StudentServiceStudentUpdateProcedure = "/users.v1.StudentService/StudentUpdate"
	// StudentServiceStudentDeleteProcedure is the fully-qualified name of the StudentService's
	// StudentDelete RPC.
	StudentServiceStudentDeleteProcedure = "/users.v1.StudentService/StudentDelete"
)

// StudentServiceClient is a client for the users.v1.StudentService service.
type StudentServiceClient interface {
	StudentCreate(context.Context, *connect.Request[v1.StudentCreateRequest]) (*connect.Response[v1.StudentCreateResponse], error)
	StudentList(context.Context, *connect.Request[v1.StudentListRequest]) (*connect.Response[v1.StudentListResponse], error)
	StudentUpdate(context.Context, *connect.Request[v1.StudentUpdateRequest]) (*connect.Response[v1.StudentUpdateResponse], error)
	StudentDelete(context.Context, *connect.Request[v1.StudentDeleteRequest]) (*connect.Response[v1.StudentDeleteResponse], error)
}

// NewStudentServiceClient constructs a client for the users.v1.StudentService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStudentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StudentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	studentServiceMethods := v1.File_users_v1_user_proto.Services().ByName("StudentService").Methods()
	return &studentServiceClient{
		studentCreate: connect.NewClient[v1.StudentCreateRequest, v1.StudentCreateResponse](
			httpClient,
			baseURL+StudentServiceStudentCreateProcedure,
			connect.WithSchema(studentServiceMethods.ByName("StudentCreate")),
			connect.WithClientOptions(opts...),
		),
		studentList: connect.NewClient[v1.StudentListRequest, v1.StudentListResponse](
			httpClient,
			baseURL+StudentServiceStudentListProcedure,
			connect.WithSchema(studentServiceMethods.ByName("StudentList")),
			connect.WithClientOptions(opts...),
		),
		studentUpdate: connect.NewClient[v1.StudentUpdateRequest, v1.StudentUpdateResponse](
			httpClient,
			baseURL+StudentServiceStudentUpdateProcedure,
			connect.WithSchema(studentServiceMethods.ByName("StudentUpdate")),
			connect.WithClientOptions(opts...),
		),
		studentDelete: connect.NewClient[v1.StudentDeleteRequest, v1.StudentDeleteResponse](
			httpClient,
			baseURL+StudentServiceStudentDeleteProcedure,
			connect.WithSchema(studentServiceMethods.ByName("StudentDelete")),
			connect.WithClientOptions(opts...),
		),
	}
}

// studentServiceClient implements StudentServiceClient.
type studentServiceClient struct {
	studentCreate *connect.Client[v1.StudentCreateRequest, v1.StudentCreateResponse]
	studentList   *connect.Client[v1.StudentListRequest, v1.StudentListResponse]
	studentUpdate *connect.Client[v1.StudentUpdateRequest, v1.StudentUpdateResponse]
	studentDelete *connect.Client[v1.StudentDeleteRequest, v1.StudentDeleteResponse]
}

// StudentCreate calls users.v1.StudentService.StudentCreate.
func (c *studentServiceClient) StudentCreate(ctx context.Context, req *connect.Request[v1.StudentCreateRequest]) (*connect.Response[v1.StudentCreateResponse], error) {
	return c.studentCreate.CallUnary(ctx, req)
}

// StudentList calls users.v1.StudentService.StudentList.
func (c *studentServiceClient) StudentList(ctx context.Context, req *connect.Request[v1.StudentListRequest]) (*connect.Response[v1.StudentListResponse], error) {
	return c.studentList.CallUnary(ctx, req)
}

// StudentUpdate calls users.v1.StudentService.StudentUpdate.
func (c *studentServiceClient) StudentUpdate(ctx context.Context, req *connect.Request[v1.StudentUpdateRequest]) (*connect.Response[v1.StudentUpdateResponse], error) {
	return c.studentUpdate.CallUnary(ctx, req)
}

// StudentDelete calls users.v1.StudentService.StudentDelete.
func (c *studentServiceClient) StudentDelete(ctx context.Context, req *connect.Request[v1.StudentDeleteRequest]) (*connect.Response[v1.StudentDeleteResponse], error) {
	return c.studentDelete.CallUnary(ctx, req)
}

// StudentServiceHandler is an implementation of the users.v1.StudentService service.
type StudentServiceHandler interface {
	StudentCreate(context.Context, *connect.Request[v1.StudentCreateRequest]) (*connect.Response[v1.StudentCreateResponse], error)
	StudentList(context.Context, *connect.Request[v1.StudentListRequest]) (*connect.Response[v1.StudentListResponse], error)
	StudentUpdate(context.Context, *connect.Request[v1.StudentUpdateRequest]) (*connect.Response[v1.StudentUpdateResponse], error)
	StudentDelete(context.Context, *connect.Request[v1.StudentDeleteRequest]) (*connect.Response[v1.StudentDeleteResponse], error)
}

// NewStudentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStudentServiceHandler(svc StudentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	studentServiceMethods := v1.File_users_v1_user_proto.Services().ByName("StudentService").Methods()
	studentServiceStudentCreateHandler := connect.NewUnaryHandler(
		StudentServiceStudentCreateProcedure,
		svc.StudentCreate,
		connect.WithSchema(studentServiceMethods.ByName("StudentCreate")),
		connect.WithHandlerOptions(opts...),
	)
	studentServiceStudentListHandler := connect.NewUnaryHandler(
		StudentServiceStudentListProcedure,
		svc.StudentList,
		connect.WithSchema(studentServiceMethods.ByName("StudentList")),
		connect.WithHandlerOptions(opts...),
	)
	studentServiceStudentUpdateHandler := connect.NewUnaryHandler(
		StudentServiceStudentUpdateProcedure,
		svc.StudentUpdate,
		connect.WithSchema(studentServiceMethods.ByName("StudentUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	studentServiceStudentDeleteHandler := connect.NewUnaryHandler(
		StudentServiceStudentDeleteProcedure,
		svc.StudentDelete,
		connect.WithSchema(studentServiceMethods.ByName("StudentDelete")),
		connect.WithHandlerOptions(opts...),
	)
	return "/users.v1.StudentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StudentServiceStudentCreateProcedure:
			studentServiceStudentCreateHandler.ServeHTTP(w, r)
		case StudentServiceStudentListProcedure:
			studentServiceStudentListHandler.ServeHTTP(w, r)
		case StudentServiceStudentUpdateProcedure:
			studentServiceStudentUpdateHandler.ServeHTTP(w, r)
		case StudentServiceStudentDeleteProcedure:
			studentServiceStudentDeleteHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStudentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStudentServiceHandler struct{}

func (UnimplementedStudentServiceHandler) StudentCreate(context.Context, *connect.Request[v1.StudentCreateRequest]) (*connect.Response[v1.StudentCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("users.v1.StudentService.StudentCreate is not implemented"))
}

func (UnimplementedStudentServiceHandler) StudentList(context.Context, *connect.Request[v1.StudentListRequest]) (*connect.Response[v1.StudentListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("users.v1.StudentService.StudentList is not implemented"))
}

func (UnimplementedStudentServiceHandler) StudentUpdate(context.Context, *connect.Request[v1.StudentUpdateRequest]) (*connect.Response[v1.StudentUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("users.v1.StudentService.StudentUpdate is not implemented"))
}

func (UnimplementedStudentServiceHandler) StudentDelete(context.Context, *connect.Request[v1.StudentDeleteRequest]) (*connect.Response[v1.StudentDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("users.v1.StudentService.StudentDelete is not implemented"))
}
