// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: attendance/v1/attendance.proto

package attendanceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wargasipil/student_pack/interfaces/attendance/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AttendanceServiceName is the fully-qualified name of the AttendanceService service.
	AttendanceServiceName = "attendance.v1.AttendanceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AttendanceServiceSubmitProcedure is the fully-qualified name of the AttendanceService's Submit
	// RPC.
	AttendanceServiceSubmitProcedure = "/attendance.v1.AttendanceService/Submit"
	// AttendanceServiceListProcedure is the fully-qualified name of the AttendanceService's List RPC.
	AttendanceServiceListProcedure = "/attendance.v1.AttendanceService/List"
)

// AttendanceServiceClient is a client for the attendance.v1.AttendanceService service.
type AttendanceServiceClient interface {
	Submit(context.Context) *connect.ClientStreamForClient[v1.SubmitRequest, v1.SubmitResponse]
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
}

// NewAttendanceServiceClient constructs a client for the attendance.v1.AttendanceService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAttendanceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AttendanceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	attendanceServiceMethods := v1.File_attendance_v1_attendance_proto.Services().ByName("AttendanceService").Methods()
	return &attendanceServiceClient{
		submit: connect.NewClient[v1.SubmitRequest, v1.SubmitResponse](
			httpClient,
			baseURL+AttendanceServiceSubmitProcedure,
			connect.WithSchema(attendanceServiceMethods.ByName("Submit")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+AttendanceServiceListProcedure,
			connect.WithSchema(attendanceServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// attendanceServiceClient implements AttendanceServiceClient.
type attendanceServiceClient struct {
	submit *connect.Client[v1.SubmitRequest, v1.SubmitResponse]
	list   *connect.Client[v1.ListRequest, v1.ListResponse]
}

// Submit calls attendance.v1.AttendanceService.Submit.
func (c *attendanceServiceClient) Submit(ctx context.Context) *connect.ClientStreamForClient[v1.SubmitRequest, v1.SubmitResponse] {
	return c.submit.CallClientStream(ctx)
}

// List calls attendance.v1.AttendanceService.List.
func (c *attendanceServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// AttendanceServiceHandler is an implementation of the attendance.v1.AttendanceService service.
type AttendanceServiceHandler interface {
	Submit(context.Context, *connect.ClientStream[v1.SubmitRequest]) (*connect.Response[v1.SubmitResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
}

// NewAttendanceServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAttendanceServiceHandler(svc AttendanceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	attendanceServiceMethods := v1.File_attendance_v1_attendance_proto.Services().ByName("AttendanceService").Methods()
	attendanceServiceSubmitHandler := connect.NewClientStreamHandler(
		AttendanceServiceSubmitProcedure,
		svc.Submit,
		connect.WithSchema(attendanceServiceMethods.ByName("Submit")),
		connect.WithHandlerOptions(opts...),
	)
	attendanceServiceListHandler := connect.NewUnaryHandler(
		AttendanceServiceListProcedure,
		svc.List,
		connect.WithSchema(attendanceServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/attendance.v1.AttendanceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AttendanceServiceSubmitProcedure:
			attendanceServiceSubmitHandler.ServeHTTP(w, r)
		case AttendanceServiceListProcedure:
			attendanceServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAttendanceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAttendanceServiceHandler struct{}

func (UnimplementedAttendanceServiceHandler) Submit(context.Context, *connect.ClientStream[v1.SubmitRequest]) (*connect.Response[v1.SubmitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("attendance.v1.AttendanceService.Submit is not implemented"))
}

func (UnimplementedAttendanceServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("attendance.v1.AttendanceService.List is not implemented"))
}
