server:
  host: "localhost"
  port: "8080"

database:
  host: "db.wtsshtlowdegadpzkjnl.supabase.co"
  port: "5432"
  username: "postgres"
  password: "facego_secret123"
  database: "postgres"
  ssl_mode: "disable"

log:
  level: "info"

storage:
  uploads_dir: "uploads"

auth:
  jwt_secret: "sample"
  admin_seed_password: "admin123"
