// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: users/v1/user.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentClass) Reset() {
	*x = StudentClass{}
	mi := &file_users_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentClass) ProtoMessage() {}

func (x *StudentClass) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentClass.ProtoReflect.Descriptor instead.
func (*StudentClass) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *StudentClass) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type StudentCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentNumber string                 `protobuf:"bytes,1,opt,name=student_number,json=studentNumber,proto3" json:"student_number,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	ParentPhone   string                 `protobuf:"bytes,3,opt,name=parent_phone,json=parentPhone,proto3" json:"parent_phone,omitempty"`
	Class         *StudentClass          `protobuf:"bytes,4,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentCreateRequest) Reset() {
	*x = StudentCreateRequest{}
	mi := &file_users_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentCreateRequest) ProtoMessage() {}

func (x *StudentCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentCreateRequest.ProtoReflect.Descriptor instead.
func (*StudentCreateRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *StudentCreateRequest) GetStudentNumber() string {
	if x != nil {
		return x.StudentNumber
	}
	return ""
}

func (x *StudentCreateRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentCreateRequest) GetParentPhone() string {
	if x != nil {
		return x.ParentPhone
	}
	return ""
}

func (x *StudentCreateRequest) GetClass() *StudentClass {
	if x != nil {
		return x.Class
	}
	return nil
}

type StudentCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     uint32                 `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentCreateResponse) Reset() {
	*x = StudentCreateResponse{}
	mi := &file_users_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentCreateResponse) ProtoMessage() {}

func (x *StudentCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentCreateResponse.ProtoReflect.Descriptor instead.
func (*StudentCreateResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *StudentCreateResponse) GetStudentId() uint32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type StudentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentListRequest) Reset() {
	*x = StudentListRequest{}
	mi := &file_users_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentListRequest) ProtoMessage() {}

func (x *StudentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentListRequest.ProtoReflect.Descriptor instead.
func (*StudentListRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{3}
}

type StudentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentListResponse) Reset() {
	*x = StudentListResponse{}
	mi := &file_users_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentListResponse) ProtoMessage() {}

func (x *StudentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentListResponse.ProtoReflect.Descriptor instead.
func (*StudentListResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{4}
}

type StudentDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentDeleteRequest) Reset() {
	*x = StudentDeleteRequest{}
	mi := &file_users_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDeleteRequest) ProtoMessage() {}

func (x *StudentDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDeleteRequest.ProtoReflect.Descriptor instead.
func (*StudentDeleteRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{5}
}

type StudentDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentDeleteResponse) Reset() {
	*x = StudentDeleteResponse{}
	mi := &file_users_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDeleteResponse) ProtoMessage() {}

func (x *StudentDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDeleteResponse.ProtoReflect.Descriptor instead.
func (*StudentDeleteResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{6}
}

type StudentUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentUpdateRequest) Reset() {
	*x = StudentUpdateRequest{}
	mi := &file_users_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentUpdateRequest) ProtoMessage() {}

func (x *StudentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentUpdateRequest.ProtoReflect.Descriptor instead.
func (*StudentUpdateRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{7}
}

type StudentUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentUpdateResponse) Reset() {
	*x = StudentUpdateResponse{}
	mi := &file_users_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentUpdateResponse) ProtoMessage() {}

func (x *StudentUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentUpdateResponse.ProtoReflect.Descriptor instead.
func (*StudentUpdateResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_user_proto_rawDescGZIP(), []int{8}
}

var File_users_v1_user_proto protoreflect.FileDescriptor

const file_users_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x13users/v1/user.proto\x12\busers.v1\"-\n" +
	"\fStudentClass\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\"\xb1\x01\n" +
	"\x14StudentCreateRequest\x12%\n" +
	"\x0estudent_number\x18\x01 \x01(\tR\rstudentNumber\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12!\n" +
	"\fparent_phone\x18\x03 \x01(\tR\vparentPhone\x12,\n" +
	"\x05class\x18\x04 \x01(\v2\x16.users.v1.StudentClassR\x05class\"6\n" +
	"\x15StudentCreateResponse\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\rR\tstudentId\"\x14\n" +
	"\x12StudentListRequest\"\x15\n" +
	"\x13StudentListResponse\"\x16\n" +
	"\x14StudentDeleteRequest\"\x17\n" +
	"\x15StudentDeleteResponse\"\x16\n" +
	"\x14StudentUpdateRequest\"\x17\n" +
	"\x15StudentUpdateResponse2\xd2\x02\n" +
	"\x0eStudentService\x12P\n" +
	"\rStudentCreate\x12\x1e.users.v1.StudentCreateRequest\x1a\x1f.users.v1.StudentCreateResponse\x12J\n" +
	"\vStudentList\x12\x1c.users.v1.StudentListRequest\x1a\x1d.users.v1.StudentListResponse\x12P\n" +
	"\rStudentUpdate\x12\x1e.users.v1.StudentUpdateRequest\x1a\x1f.users.v1.StudentUpdateResponse\x12P\n" +
	"\rStudentDelete\x12\x1e.users.v1.StudentDeleteRequest\x1a\x1f.users.v1.StudentDeleteResponseB\x98\x01\n" +
	"\fcom.users.v1B\tUserProtoP\x01Z<github.com/wargasipil/student_pack/interfaces/users/v1;users\xa2\x02\x03UXX\xaa\x02\bUsers.V1\xca\x02\bUsers\\V1\xe2\x02\x14Users\\V1\\GPBMetadata\xea\x02\tUsers::V1b\x06proto3"

var (
	file_users_v1_user_proto_rawDescOnce sync.Once
	file_users_v1_user_proto_rawDescData []byte
)

func file_users_v1_user_proto_rawDescGZIP() []byte {
	file_users_v1_user_proto_rawDescOnce.Do(func() {
		file_users_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_user_proto_rawDesc), len(file_users_v1_user_proto_rawDesc)))
	})
	return file_users_v1_user_proto_rawDescData
}

var file_users_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_users_v1_user_proto_goTypes = []any{
	(*StudentClass)(nil),          // 0: users.v1.StudentClass
	(*StudentCreateRequest)(nil),  // 1: users.v1.StudentCreateRequest
	(*StudentCreateResponse)(nil), // 2: users.v1.StudentCreateResponse
	(*StudentListRequest)(nil),    // 3: users.v1.StudentListRequest
	(*StudentListResponse)(nil),   // 4: users.v1.StudentListResponse
	(*StudentDeleteRequest)(nil),  // 5: users.v1.StudentDeleteRequest
	(*StudentDeleteResponse)(nil), // 6: users.v1.StudentDeleteResponse
	(*StudentUpdateRequest)(nil),  // 7: users.v1.StudentUpdateRequest
	(*StudentUpdateResponse)(nil), // 8: users.v1.StudentUpdateResponse
}
var file_users_v1_user_proto_depIdxs = []int32{
	0, // 0: users.v1.StudentCreateRequest.class:type_name -> users.v1.StudentClass
	1, // 1: users.v1.StudentService.StudentCreate:input_type -> users.v1.StudentCreateRequest
	3, // 2: users.v1.StudentService.StudentList:input_type -> users.v1.StudentListRequest
	7, // 3: users.v1.StudentService.StudentUpdate:input_type -> users.v1.StudentUpdateRequest
	5, // 4: users.v1.StudentService.StudentDelete:input_type -> users.v1.StudentDeleteRequest
	2, // 5: users.v1.StudentService.StudentCreate:output_type -> users.v1.StudentCreateResponse
	4, // 6: users.v1.StudentService.StudentList:output_type -> users.v1.StudentListResponse
	8, // 7: users.v1.StudentService.StudentUpdate:output_type -> users.v1.StudentUpdateResponse
	6, // 8: users.v1.StudentService.StudentDelete:output_type -> users.v1.StudentDeleteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_users_v1_user_proto_init() }
func file_users_v1_user_proto_init() {
	if File_users_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_user_proto_rawDesc), len(file_users_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_v1_user_proto_goTypes,
		DependencyIndexes: file_users_v1_user_proto_depIdxs,
		MessageInfos:      file_users_v1_user_proto_msgTypes,
	}.Build()
	File_users_v1_user_proto = out.File
	file_users_v1_user_proto_goTypes = nil
	file_users_v1_user_proto_depIdxs = nil
}
